# Generated by Django 4.0.3 on 2022-03-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('text_input', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
